version: '3'

services:
  rasa_actions:
    build:
      context: .
      dockerfile: Dockerfile.actions
    volumes:
      - ./src:/app
    networks:
      - rasa-network
  rasa_shell:
    build:
      context: .
      dockerfile: Dockerfile.shell
    volumes:
      - ./src:/app
    depends_on:
      - rasa_actions
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge
